# Generated by Django 5.2.1 on 2025-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefere não informar')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
